version: '3'
services:
  server:
    build:
      context: ./server
    image: bsmsultani/cab432-assignment1_server:latest
    ports:
      - "3001:3001"
    depends_on:
      - client
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
    image: bsmsultani/cab432-assignment1_client:latest
    ports:
      - "3000:3000"
